import Header from './header'
import Head from 'next/head'
import styles from '../styles/Home.module.scss';
export default function Layout({ children } : { children:JSX.Element }) {
  return (
    <>
      <Head>
        <title>AoS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>{children}</main>
      {/* <Footer /> */}
    </>
  )
}   